# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages

before_install:
  - sudo apt-get update
  - sudo apt-get -y install curl
  - cd ~/
  - curl https://bertini.nd.edu/BertiniLinux64_v1.6.tar.gz -o BertiniLinux64_v1.6.tar.gz
  - tar -xf BertiniLinux64_v1.6.tar.gz
  - cd BertiniLinux64_v1.6
  - export BERTINI=~/BertiniLinux64_v1.6

install:
  - Rscript -e 'install.packages("devtools");devtools::install_deps()'

script:
  - Rscript -e 'devtools::check()'

after_script:
  - tar -ztvf bertini_*.tar.gz
  - echo ${NOT_CRAN}

after_success:
  - travis_wait 40 tar -C .. -xf $PKG_TARBALL

after_failure:
  - cat bertini.Rcheck/00*

#
jobs:
  r_github_packages:
  - dkahle/mpoly
  - dkahle/latte
  - dkahle/bertini
  - coneill-math/m2r

  include:
  - r: devel
  - r: release

jobs:
  include:
  - r: devel
  - r: release
