# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

before_install:
  - apt-get update
  - apt-get -y install curl
  - cd ~/
  - curl https://bertini.nd.edu/BertiniLinux64_v1.6.tar.gz -o BertiniLinux64_v1.6.tar.gz
  - tar -xf BertiniLinux64_v1.6.tar.gz
  - cd BertiniLinux64_v1.6


jobs:
  include:
  - r: devel
  - r: release
    env:
      - BERTINI=~/BertiniLinux64_v1.6
